run:

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

linters:
  enable-all: true
  disable:
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - exhaustive
    - exhaustruct
    - err113
    - errorlint
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - gomnd
    - gomoddirectives # I think it's broken
    - gosec
    - gosmopolitan
    - govet
    - inamedparam # oh, sod off
    - interfacebloat 
    - ireturn # No, I _LIKE_ returning interfaces
    - lll
    - maintidx # Do this in code review
    - makezero
    - mnd # TODO: re-enable when we can check again
    - nonamedreturns
    - nakedret
    - nestif
    - nlreturn
    - paralleltest
    - perfsprint
    - testifylint # TODO: re-enable when we can check again
    - tagliatelle
    - testpackage
    - thelper    # Tests are fine
    - varnamelen # Short names are ok
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    # not needed
    - path: /*.go
      text: "ST1003: should not use underscores in package names"
      linters:
        - stylecheck
    - path: /*.go
      text: "don't use an underscore in package name"
      linters:
        - revive
    - path: /main.go
      linters:
        - errcheck
    - path: internal/codegen/codegen.go
      linters:
        - errcheck
    - path: internal/jwxtest/jwxtest.go
      linters:
        - errcheck
        - errchkjson
        - forcetypeassert
    - path: /*_test.go
      linters:
        - errcheck
        - errchkjson
        - forcetypeassert
    - path: /*_example_test.go
      linters:
        - forbidigo
    - path: cmd/jwx/jwx.go
      linters:
        - forbidigo
    - path: /*_test.go
      text: "var-naming: "
      linters:
        - revive

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

