run:

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow

linters:
  enable-all: true
  disable:
    - gomnd
    - gocritic
    - lll
    - gochecknoinits
    - wsl
    - nakedret
    - funlen
    - gochecknoglobals
    - gocognit
    - godox
    - gocyclo
    - dupl
    - gosec
    - testpackage
    - godot
    - nestif
    - goerr113
    - nlreturn

issues:
  exclude-rules:
    # not needed
    - path: /*.go
      text: "ST1003: should not use underscores in package names"
      linters:
        - stylecheck
    - path: /*.go
      text: "don't use an underscore in package name"
      linters:
        - golint
    - path: /main.go
      linters:
        - errcheck
    - path: internal/codegen/codegen.go
      linters:
        - errcheck
    - path: /*_test.go
      linters:
        - errcheck

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

