//go:build go1.27

// Code generated by tools/cmd/genjwa/main.go. DO NOT EDIT

package jwa_test

import (
	"encoding/json"
	"strconv"
	"testing"

	"github.com/lestrrat-go/jwx/v4/jwa"
	"github.com/stretchr/testify/require"
)

func TestSignatureAlgorithm_go127(t *testing.T) {
	t.Parallel()
	t.Run(`Lookup the object`, func(t *testing.T) {
		t.Parallel()
		v, ok := jwa.LookupSignatureAlgorithm("ML-DSA-44")
		require.True(t, ok, `Lookup should succeed`)
		require.Equal(t, jwa.MLDSA44(), v, `Lookup value should be equal to constant`)
	})
	t.Run(`Unmarshal the string ML-DSA-44`, func(t *testing.T) {
		t.Parallel()
		var dst jwa.SignatureAlgorithm
		require.NoError(t, json.Unmarshal([]byte(strconv.Quote("ML-DSA-44")), &dst), `UnmarshalJSON is successful`)
		require.Equal(t, jwa.MLDSA44(), dst, `unmarshaled value should be equal to constant`)
	})
	t.Run(`stringification for ML-DSA-44`, func(t *testing.T) {
		t.Parallel()
		require.Equal(t, "ML-DSA-44", jwa.MLDSA44().String(), `stringified value matches`)
	})
	t.Run(`Lookup the object`, func(t *testing.T) {
		t.Parallel()
		v, ok := jwa.LookupSignatureAlgorithm("ML-DSA-65")
		require.True(t, ok, `Lookup should succeed`)
		require.Equal(t, jwa.MLDSA65(), v, `Lookup value should be equal to constant`)
	})
	t.Run(`Unmarshal the string ML-DSA-65`, func(t *testing.T) {
		t.Parallel()
		var dst jwa.SignatureAlgorithm
		require.NoError(t, json.Unmarshal([]byte(strconv.Quote("ML-DSA-65")), &dst), `UnmarshalJSON is successful`)
		require.Equal(t, jwa.MLDSA65(), dst, `unmarshaled value should be equal to constant`)
	})
	t.Run(`stringification for ML-DSA-65`, func(t *testing.T) {
		t.Parallel()
		require.Equal(t, "ML-DSA-65", jwa.MLDSA65().String(), `stringified value matches`)
	})
	t.Run(`Lookup the object`, func(t *testing.T) {
		t.Parallel()
		v, ok := jwa.LookupSignatureAlgorithm("ML-DSA-87")
		require.True(t, ok, `Lookup should succeed`)
		require.Equal(t, jwa.MLDSA87(), v, `Lookup value should be equal to constant`)
	})
	t.Run(`Unmarshal the string ML-DSA-87`, func(t *testing.T) {
		t.Parallel()
		var dst jwa.SignatureAlgorithm
		require.NoError(t, json.Unmarshal([]byte(strconv.Quote("ML-DSA-87")), &dst), `UnmarshalJSON is successful`)
		require.Equal(t, jwa.MLDSA87(), dst, `unmarshaled value should be equal to constant`)
	})
	t.Run(`stringification for ML-DSA-87`, func(t *testing.T) {
		t.Parallel()
		require.Equal(t, "ML-DSA-87", jwa.MLDSA87().String(), `stringified value matches`)
	})
	t.Run(`check symmetric values`, func(t *testing.T) {
		t.Parallel()
		t.Run(`MLDSA44`, func(t *testing.T) {
			require.False(t, jwa.MLDSA44().IsSymmetric(), `jwa.MLDSA44 returns expected value`)
		})
		t.Run(`MLDSA65`, func(t *testing.T) {
			require.False(t, jwa.MLDSA65().IsSymmetric(), `jwa.MLDSA65 returns expected value`)
		})
		t.Run(`MLDSA87`, func(t *testing.T) {
			require.False(t, jwa.MLDSA87().IsSymmetric(), `jwa.MLDSA87 returns expected value`)
		})
	})
}
