// Code generated by tools/cmd/genreadfile/main.go. DO NOT EDIT.

package jwk

import (
	"io/fs"
)

func ParseFS(fsys fs.FS, path string, options ...ParseOption) (Set, error) {
	f, err := fsys.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	return ParseReader(f, options...)
}
