// Code generated by tools/cmd/genoptions/main.go. DO NOT EDIT.

package jwk

import (
	"crypto"

	"github.com/lestrrat-go/jwx/v4/internal/json"
	"github.com/lestrrat-go/option/v3"
)

type Option = option.Interface

type AssignKeyIDOption interface {
	Option
	assignKeyIDOption()
}

type assignKeyIDOption struct {
	Option
}

func (*assignKeyIDOption) assignKeyIDOption() {}

// GlobalOption is a type of Option that can be passed to `jwk.Settings()` to
// change the global configuration of the jwk package.
type GlobalOption interface {
	Option
	globalOption()
}

type globalOption struct {
	Option
}

func (*globalOption) globalOption() {}

// GlobalParseOption describes an Option that can be passed to both
// `jwk.Settings()` (to change the default globally) and
// `jwk.Parse()` / `jwk.ParseReader()` / `jwk.ParseString()` (to
// override per call).
type GlobalParseOption interface {
	Option
	globalOption()
	parseOption()
}

type globalParseOption struct {
	Option
}

func (*globalParseOption) globalOption() {}

func (*globalParseOption) parseOption() {}

// ParseOption is a type of Option that can be passed to `jwk.Parse()`
type ParseOption interface {
	Option
	parseOption()
}

type parseOption struct {
	Option
}

func (*parseOption) parseOption() {}

// PublicSetOption is a type of Option that can be passed to `jwk.PublicSetOf()`
type PublicSetOption interface {
	Option
	publicSetOption()
}

type publicSetOption struct {
	Option
}

func (*publicSetOption) publicSetOption() {}

type identAllowSymmetric struct{}
type identForceAssign struct{}
type identIgnoreParseError struct{}
type identLocalRegistry struct{}
type identMaxKeys struct{}
type identMinRSAModulusBits struct{}
type identMinRSAPublicExponent struct{}
type identRejectDuplicateKID struct{}
type identStrictKeyUsage struct{}
type identThumbprintHash struct{}
type identX509 struct{}

func (identAllowSymmetric) String() string {
	return "WithAllowSymmetric"
}

func (identForceAssign) String() string {
	return "WithForceAssign"
}

func (identIgnoreParseError) String() string {
	return "WithIgnoreParseError"
}

func (identLocalRegistry) String() string {
	return "withLocalRegistry"
}

func (identMaxKeys) String() string {
	return "WithMaxKeys"
}

func (identMinRSAModulusBits) String() string {
	return "WithMinRSAModulusBits"
}

func (identMinRSAPublicExponent) String() string {
	return "WithMinRSAPublicExponent"
}

func (identRejectDuplicateKID) String() string {
	return "WithRejectDuplicateKID"
}

func (identStrictKeyUsage) String() string {
	return "WithStrictKeyUsage"
}

func (identThumbprintHash) String() string {
	return "WithThumbprintHash"
}

func (identX509) String() string {
	return "WithX509"
}

// WithAllowSymmetric controls whether `jwk.PublicSetOf` tolerates
// symmetric (oct) keys in the input set.
//
// By default this option is false: a symmetric key in the input is
// an error, because a symmetric key has no public form — its
// "public" representation is the secret itself. Passing such a set
// through `PublicSetOf` silently and then publishing the result
// (e.g. as `/.well-known/jwks.json`) would leak HMAC secret material.
//
// Pass `WithAllowSymmetric(true)` only if you are certain the
// resulting set will not be published. When true, symmetric keys
// are passed through unchanged, matching the legacy behavior.
func WithAllowSymmetric(v bool) PublicSetOption {
	return &publicSetOption{option.New(identAllowSymmetric{}, v)}
}

// WithForceAssign forces `jwk.AssignKeyID` to recompute and overwrite
// the `kid` header even when the key already has one. The default
// behavior preserves any existing `kid`; use this option to upgrade
// the thumbprint hash (e.g. with `jwk.WithThumbprintHash`) or to
// refresh a `kid` after mutating a key field that invalidates the
// cached thumbprint.
func WithForceAssign(v bool) AssignKeyIDOption {
	return &assignKeyIDOption{option.New(identForceAssign{}, v)}
}

// WithIgnoreParseError is only applicable when used with `jwk.Parse()`
// (i.e. to parse JWK sets). If passed to `jwk.ParseKey()`, the function
// will return an error no matter what the input is.
//
// DO NOT USE WITHOUT EXHAUSTING ALL OTHER ROUTES FIRST.
//
// The option specifies that errors found during parsing of individual
// keys are ignored. For example, if you had keys A, B, C where B is
// invalid (e.g. it does not contain the required fields), then the
// resulting JWKS will contain keys A and C only.
//
// This options exists as an escape hatch for those times when a
// key in a JWKS that is irrelevant for your use case is causing
// your JWKS parsing to fail, and you want to get to the rest of the
// keys in the JWKS.
//
// Again, DO NOT USE unless you have exhausted all other routes.
// When you use this option, you will not be able to tell if you are
// using a faulty JWKS, except for when there are JSON syntax errors.
func WithIgnoreParseError(v bool) ParseOption {
	return &parseOption{option.New(identIgnoreParseError{}, v)}
}

// This option is only available for internal code. Users don't get to play with it
func withLocalRegistry(v *json.Registry) ParseOption {
	return &parseOption{option.New(identLocalRegistry{}, v)}
}

// WithMaxKeys specifies the maximum number of keys allowed in a JWK
// set passed to `jwk.Parse()` / `jwk.ParseReader()` / `jwk.ParseString()`.
// If the "keys" array of a JSON-encoded JWKS, or the number of PEM
// blocks in an X.509-encoded input, exceeds this value, parsing
// returns an error. The default is 1000.
//
// This option can be passed to `jwk.Settings()` to change the default
// globally, or to `jwk.Parse()` / `jwk.ParseReader()` /
// `jwk.ParseString()` for a per-call override. A non-positive value
// is rejected.
//
// The cap defends against amplification: each entry triggers a
// probe + unmarshal + validation, each of which allocates. Bounding
// raw input bytes remains the caller's responsibility — see
// docs/13-input-size.md.
func WithMaxKeys(v int) GlobalParseOption {
	return &globalParseOption{option.New(identMaxKeys{}, v)}
}

// WithMinRSAModulusBits specifies the minimum RSA modulus size, in bits,
// accepted by JWK validation and raw/PEM/X.509 import.
//
// The default is 2048. Lower this only for legacy interoperability with
// older key material. A value of 0 disables the modulus-size floor.
func WithMinRSAModulusBits(v int) GlobalOption {
	return &globalOption{option.New(identMinRSAModulusBits{}, v)}
}

// WithMinRSAPublicExponent specifies the minimum RSA public exponent
// accepted by JWK validation and raw/PEM/X.509 import.
//
// The default is 3. The exponent must still be odd and fit in a Go `int`.
// Lower this only for legacy interoperability. A value of 0 disables the
// minimum-exponent floor.
func WithMinRSAPublicExponent(v int) GlobalOption {
	return &globalOption{option.New(identMinRSAPublicExponent{}, v)}
}

// WithRejectDuplicateKID instructs `jwk.Parse()` /
// `jwk.ParseReader()` / `jwk.ParseString()` and the companion
// `Set.UnmarshalJSON()` to return an error when the JWKS contains
// two or more keys with the same non-empty `kid`. Keys without a
// kid are not considered.
//
// Default is false — first-match-wins is retained for
// compatibility with RFC 7517 (which permits, but does not
// mandate, unique kids) and with existing callers that rely on
// `(jwk.Set).LookupKeyID` returning the first entry. Use this
// option when your issuer should guarantee kid uniqueness and a
// duplicate is a sign of misconfiguration worth surfacing at
// parse time rather than at verify time.
//
// Can be set globally via `jwk.Settings()` or per-call on
// `jwk.Parse()` / `jwk.ParseReader()` / `jwk.ParseString()`.
//
// This does not affect `(*Set).AddKey` — programmatic additions
// remain permissive (AddKey dedupes only by pointer identity).
func WithRejectDuplicateKID(v bool) GlobalParseOption {
	return &globalParseOption{option.New(identRejectDuplicateKID{}, v)}
}

// WithStrictKeyUsage specifies if during JWK parsing, the "use" field
// should be confined to the values that have been registered via
// `jwk.RegisterKeyType()`. By default this option is true, and the
// initial allowed values are "use" and "enc" only.
//
// If this option is set to false, then the "use" field can be any
// value. If this options is set to true, then the "use" field must
// be one of the registered values, and otherwise an error will be
// reported during parsing / assignment to `jwk.KeyUsageType`
func WithStrictKeyUsage(v bool) GlobalOption {
	return &globalOption{option.New(identStrictKeyUsage{}, v)}
}

func WithThumbprintHash(v crypto.Hash) AssignKeyIDOption {
	return &assignKeyIDOption{option.New(identThumbprintHash{}, v)}
}

// WithX509 specifies that the input to `Parse()` / `ParseKey()` is a
// PEM-framed X.509-encoded key (or key set). Custom PEM block types can
// be handled by registering decoders via
// `jwkbb.RegisterX509Decoder`.
func WithX509(v bool) ParseOption {
	return &parseOption{option.New(identX509{}, v)}
}
