// Code generated by tools/cmd/genoptions/main.go. DO NOT EDIT.

package jwk

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestOptionIdent(t *testing.T) {
	require.Equal(t, "WithAllowSymmetric", identAllowSymmetric{}.String())
	require.Equal(t, "WithFS", identFS{}.String())
	require.Equal(t, "WithFetchWhitelist", identFetchWhitelist{}.String())
	require.Equal(t, "WithForceAssign", identForceAssign{}.String())
	require.Equal(t, "WithHTTPClient", identHTTPClient{}.String())
	require.Equal(t, "WithIgnoreParseError", identIgnoreParseError{}.String())
	require.Equal(t, "withLocalRegistry", identLocalRegistry{}.String())
	require.Equal(t, "WithMaxFetchBodySize", identMaxFetchBodySize{}.String())
	require.Equal(t, "WithPEM", identPEM{}.String())
	require.Equal(t, "WithPEMDecoder", identPEMDecoder{}.String())
	require.Equal(t, "WithStrictKeyUsage", identStrictKeyUsage{}.String())
	require.Equal(t, "WithThumbprintHash", identThumbprintHash{}.String())
	require.Equal(t, "WithWaitReady", identWaitReady{}.String())
	require.Equal(t, "WithX509", identX509{}.String())
}
