// Generated by "sketch" utility. DO NOT EDIT
package jwk

import (
	"encoding/json"
	"fmt"
)

type fieldPair struct {
	Name  string
	Value interface{}
}

func defaultDecodeExtra(name string, dec *json.Decoder, dst interface{}) error {
	if err := dec.Decode(dst); err != nil {
		return fmt.Errorf(`failed to decode value for %q: %w`, name, err)
	}
	return nil
}
