package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/lestrrat-go/codegen"
)

type readfileDefinition struct {
	Filename   string
	Package    string
	ReturnType string
}

func runReadFile(args []string) error {
	definitions := []readfileDefinition{
		{
			Package:    "jwk",
			ReturnType: "Set",
			Filename:   "jwk/io.go",
		},
		{
			Package:    "jws",
			ReturnType: "*Message",
			Filename:   "jws/io.go",
		},
		{
			Package:    "jwe",
			ReturnType: "*Message",
			Filename:   "jwe/io.go",
		},
		{
			Package:    "jwt",
			ReturnType: "Token",
			Filename:   "jwt/io.go",
		},
	}

	for _, def := range definitions {
		if err := generateReadFile(def); err != nil {
			return err
		}
	}
	return nil
}

func generateReadFile(def readfileDefinition) error {
	var buf bytes.Buffer
	o := codegen.NewOutput(&buf)

	o.LL("// Code generated by tools/cmd/genreadfile/main.go. DO NOT EDIT.")
	o.LL("package %s", def.Package)

	o.WriteImports("io/fs")

	o.LL("func ParseFS(fsys fs.FS, path string, options ...ParseOption) (%s, error) {", def.ReturnType)
	o.L("f, err := fsys.Open(path)")
	o.L("if err != nil {")
	o.L("return nil, err")
	o.L("}")
	o.L("defer f.Close()")
	o.LL("return ParseReader(f, options...)")
	o.L("}")
	if err := o.WriteFile(def.Filename, codegen.WithFormatCode(true)); err != nil {
		if cfe, ok := err.(codegen.CodeFormatError); ok {
			fmt.Fprint(os.Stderr, cfe.Source())
		}
		return fmt.Errorf(`failed to write to %s: %w`, def.Filename, err)
	}
	return nil
}
