load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "jwkunsafe",
    srcs = ["jwkunsafe.go"],
    importpath = "github.com/lestrrat-go/jwx/v3/jwk/jwkunsafe",
    visibility = ["//visibility:public"],
    deps = [
        "//jwa",
        "//jwk",
        "//jwk/internal/registry",
    ],
)

alias(
    name = "go_default_library",
    actual = ":jwkunsafe",
    visibility = ["//visibility:public"],
)

go_test(
    name = "jwkunsafe_test",
    srcs = ["jwkunsafe_test.go"],
    deps = [
        ":jwkunsafe",
        "//jwa",
        "@com_github_stretchr_testify//require",
    ],
)
