name: CI
on:
  pull_request:
    branches:
      - develop/v*
  push:
    branches:
      - develop/v*
env:
  GOEXPERIMENT: jsonv2

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
          check-latest: true
      - name: Test with coverage
        run: go test -v -race -coverprofile=coverage.out ./...
      - name: Check go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
