load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "keygen",
    srcs = [
        "interface.go",
        "keygen.go",
    ],
    importpath = "github.com/lestrrat-go/jwx/v3/jwe/internal/keygen",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/tokens",
        "//jwe/internal/concatkdf",
        "//jwk",
    ],
)

alias(
    name = "go_default_library",
    actual = ":keygen",
    visibility = ["//jwe:__subpackages__"],
)

go_test(
    name = "keygen_test",
    srcs = ["keygen_test.go"],
    deps = [
        ":keygen",
        "@com_github_stretchr_testify//require",
    ],
)
