name: Auto-Doc
on:
  pull_request:
    branches:
      - develop/v2
      - develop/v3
    types:
      - closed

jobs:
  autodoc:
    runs-on: ubuntu-latest
    name: "Run commands to generate documentation"
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Process markdown files
        run: |
          find . -name '*.md' | xargs perl tools/autodoc.pl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
