name: Auto-Doc
on:
  pull_request:
    branches:
      - develop/v2
    types:
      - closed

jobs:
  autodoc:
    runs-on: ubuntu-latest
    name: "Run commands to generate documentation"
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Process markdown files
        run: |
          find . -name '*.md' | xargs perl tools/autodoc.pl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
