name: Bazel
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Bazel"
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Cache Bazel
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: ${{ runner.os }}-bazel-${{ hashFiles('MODULE.bazel.lock', '**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2 # v3.0.0
      - run: bazel build //...
      - run: bazel mod tidy
      - name: Check difference between generation code and commit code
        run: make check_diffs
