name: merge dependabot
on: 
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    if: ${{github.event.label.name == 'dependabot'}}
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - run: |
          make tidy
      - run: |
          make test
      - run: |
          bazel mod tidy
      - run: |
          bazel build //...
      - run: |
          git config --local user.name 'Daisuke Maki'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Run tidy / bazel+gazelle"
            git push origin "HEAD:${{ github.event.pull_request.head.ref }}"
          else
            echo "No changes to commit"
          fi
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
