name: dependabot tidy
on: 
  pull_request_target:
    types: [labeled]

permissions:
  contents: write

jobs:
  merge:
    if: ${{ github.event.label.name == 'dependabot' && github.event.pull_request.user.login == 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - run: |
          make tidy
      - run: |
          make test
      - name: Bazel tidy (bzlmod)
        if: github.event.pull_request.base.ref != 'develop/v2'
        run: |
          bazel mod tidy
      - name: Bazel tidy (WORKSPACE)
        if: github.event.pull_request.base.ref == 'develop/v2'
        run: |
          bazel run //:gazelle-update-repos
      - run: |
          bazel build //...
      - run: |
          git config --local user.name 'Daisuke Maki'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Run tidy / bazel+gazelle"
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "HEAD:${PR_HEAD_REF}"
          else
            echo "No changes to commit"
          fi
        env:
          PR_HEAD_REF: ${{github.event.pull_request.head.ref}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
