name: lint
on: [push]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-go@a5f9b05d2d216f63e13859e0d847461041025775 # v6.1.0
        with:
          go-version-file: "go.mod"
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
      - name: Run go vet
        run: |
          go vet ./...
