# Smoke tests only run on non-master branches. Smoke tests cut
# some corners by running selected tests in parallel (to shave off
# some execution time)
# Once a pull request is merged to master, workflows/ci.yml is run
name: Smoke Tests
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_tags: [ 'stdlib', 'goccy', 'es256k', 'alltags' ]
        go: [ '1.25' ]
    name: "Smoke [ Go ${{ matrix.go }} / Tags ${{ matrix.go_tags }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Check documentation generator
        run: |
          find . -name '*.md' | xargs env AUTODOC_DRYRUN=1 perl tools/autodoc.pl
      - name: Cache Go modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/bazel
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go stable version
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Install stringer
        run: go install golang.org/x/tools/cmd/stringer@v0.42.0
      - name: Install jose
        run: sudo apt-get install -y --no-install-recommends jose
      - run: make generate
      - name: Check difference between generation code and commit code
        run: make check_diffs
      - name: make tidy
        run: make tidy
      - name: Run smoke tests
        run: make smoke-${{ matrix.go_tags }}
      - uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2 # v3.0.0
      - run: bazel build //...
